[project]
name = "basecamp2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.4"
dependencies = [
    "fastapi>=0.139.2",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "streamlit>=1.59.2",
    "uvicorn>=0.51.0",
    "xlsxwriter>=3.2.9",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.1",
]
